//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Extended_Controls.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color MenuStrip_ForeColor {
            get {
                return ((global::System.Drawing.Color)(this["MenuStrip_ForeColor"]));
            }
            set {
                this["MenuStrip_ForeColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("WhiteSmoke")]
        public global::System.Drawing.Color MenuStrip_MenuStripGradientBegin {
            get {
                return ((global::System.Drawing.Color)(this["MenuStrip_MenuStripGradientBegin"]));
            }
            set {
                this["MenuStrip_MenuStripGradientBegin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("WhiteSmoke")]
        public global::System.Drawing.Color MenuStrip_MenuStripGradientEnd {
            get {
                return ((global::System.Drawing.Color)(this["MenuStrip_MenuStripGradientEnd"]));
            }
            set {
                this["MenuStrip_MenuStripGradientEnd"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LightBlue")]
        public global::System.Drawing.Color MenuStrip_MenuItemBorder {
            get {
                return ((global::System.Drawing.Color)(this["MenuStrip_MenuItemBorder"]));
            }
            set {
                this["MenuStrip_MenuItemBorder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LightBlue")]
        public global::System.Drawing.Color MenuStrip_MenuItemSelectedGradientBegin {
            get {
                return ((global::System.Drawing.Color)(this["MenuStrip_MenuItemSelectedGradientBegin"]));
            }
            set {
                this["MenuStrip_MenuItemSelectedGradientBegin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("WhiteSmoke")]
        public global::System.Drawing.Color MenuStrip_MenuItemSelectedGradientEnd {
            get {
                return ((global::System.Drawing.Color)(this["MenuStrip_MenuItemSelectedGradientEnd"]));
            }
            set {
                this["MenuStrip_MenuItemSelectedGradientEnd"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LightBlue")]
        public global::System.Drawing.Color MenuStrip_MenuItemPressedGradientBegin {
            get {
                return ((global::System.Drawing.Color)(this["MenuStrip_MenuItemPressedGradientBegin"]));
            }
            set {
                this["MenuStrip_MenuItemPressedGradientBegin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("WhiteSmoke")]
        public global::System.Drawing.Color MenuStrip_MenuItemPressedGradientEnd {
            get {
                return ((global::System.Drawing.Color)(this["MenuStrip_MenuItemPressedGradientEnd"]));
            }
            set {
                this["MenuStrip_MenuItemPressedGradientEnd"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LightBlue")]
        public global::System.Drawing.Color MenuStrip_MenuBorder {
            get {
                return ((global::System.Drawing.Color)(this["MenuStrip_MenuBorder"]));
            }
            set {
                this["MenuStrip_MenuBorder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LightBlue")]
        public global::System.Drawing.Color MenuStrip_MenuItemSelected {
            get {
                return ((global::System.Drawing.Color)(this["MenuStrip_MenuItemSelected"]));
            }
            set {
                this["MenuStrip_MenuItemSelected"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("WhiteSmoke")]
        public global::System.Drawing.Color MenuStrip_ImageMarginGradientBegin {
            get {
                return ((global::System.Drawing.Color)(this["MenuStrip_ImageMarginGradientBegin"]));
            }
            set {
                this["MenuStrip_ImageMarginGradientBegin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("WhiteSmoke")]
        public global::System.Drawing.Color MenuStrip_ImageMarginGradientMiddle {
            get {
                return ((global::System.Drawing.Color)(this["MenuStrip_ImageMarginGradientMiddle"]));
            }
            set {
                this["MenuStrip_ImageMarginGradientMiddle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("WhiteSmoke")]
        public global::System.Drawing.Color MenuStrip_ImageMarginGradientEnd {
            get {
                return ((global::System.Drawing.Color)(this["MenuStrip_ImageMarginGradientEnd"]));
            }
            set {
                this["MenuStrip_ImageMarginGradientEnd"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color MenuStrip_Selected_ForeColor {
            get {
                return ((global::System.Drawing.Color)(this["MenuStrip_Selected_ForeColor"]));
            }
            set {
                this["MenuStrip_Selected_ForeColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color ContextStrip_ForeColor {
            get {
                return ((global::System.Drawing.Color)(this["ContextStrip_ForeColor"]));
            }
            set {
                this["ContextStrip_ForeColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color ContextStrip_Selected_ForeColor {
            get {
                return ((global::System.Drawing.Color)(this["ContextStrip_Selected_ForeColor"]));
            }
            set {
                this["ContextStrip_Selected_ForeColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LightBlue")]
        public global::System.Drawing.Color ContextStrip_MenuItemBorder {
            get {
                return ((global::System.Drawing.Color)(this["ContextStrip_MenuItemBorder"]));
            }
            set {
                this["ContextStrip_MenuItemBorder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LightBlue")]
        public global::System.Drawing.Color ContextStrip_MenuBorder {
            get {
                return ((global::System.Drawing.Color)(this["ContextStrip_MenuBorder"]));
            }
            set {
                this["ContextStrip_MenuBorder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LightBlue")]
        public global::System.Drawing.Color ContextStrip_MenuItemSelected {
            get {
                return ((global::System.Drawing.Color)(this["ContextStrip_MenuItemSelected"]));
            }
            set {
                this["ContextStrip_MenuItemSelected"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("WhiteSmoke")]
        public global::System.Drawing.Color ContextStrip_ImageMarginGradientBegin {
            get {
                return ((global::System.Drawing.Color)(this["ContextStrip_ImageMarginGradientBegin"]));
            }
            set {
                this["ContextStrip_ImageMarginGradientBegin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("WhiteSmoke")]
        public global::System.Drawing.Color ContextStrip_ImageMarginGradientMiddle {
            get {
                return ((global::System.Drawing.Color)(this["ContextStrip_ImageMarginGradientMiddle"]));
            }
            set {
                this["ContextStrip_ImageMarginGradientMiddle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("WhiteSmoke")]
        public global::System.Drawing.Color ContextStrip_ImageMarginGradientEnd {
            get {
                return ((global::System.Drawing.Color)(this["ContextStrip_ImageMarginGradientEnd"]));
            }
            set {
                this["ContextStrip_ImageMarginGradientEnd"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("WhiteSmoke")]
        public global::System.Drawing.Color ContextStrip_MenuBackground {
            get {
                return ((global::System.Drawing.Color)(this["ContextStrip_MenuBackground"]));
            }
            set {
                this["ContextStrip_MenuBackground"] = value;
            }
        }
    }
}
